name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.ik8s.cc", custom_domain = true },
  { pattern = "quey.ik8s.cc", custom_domain = true },
  { pattern = "gcr.ik8s.cc", custom_domain = true },
  { pattern = "k8s-gcr.ik8s.cc", custom_domain = true },
  { pattern = "k8s.ik8s.cc", custom_domain = true },
  { pattern = "ghcr.ik8s.cc", custom_domain = true },
  { pattern = "cloudsmith.ik8s.cc", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.ik8s.cc", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
